Update code documentation and resolve a module incompatibility
afids/autoafids_prep pull request #5
Opened 2024-09-09 18:55 UTC by Dhananjhay

This PR primarily updates the code documentation and README file to organize the repository's development. It also resolves simpleITK module incompatibility with the rest of the package.

2024-09-10 15:29 UTC, ataha24 commented on README.md
> +Robarts Research Institute Team - 2023-2024
update to: 
"AIMS Lab Research Team at the Robarts Research Institute - 2023-2024"

2024-09-10 15:30 UTC, ataha24 commented on README.md
> +This Python package is a data processing pipeline based on Snakemake and SnakeBIDS workflow management tools to prepare data for a Convolutional Neural Network (CNN) deep learning model [AFIDS-CNN](h
AFIDS-CNN --> afids-CNN

2024-09-10 15:32 UTC, ataha24 commented on README.md
> +1. Performs rigid registraion to MNI template.
1. Performs rigid registration (i.e., 6 d.o.f) from MNI template to Native space.

2024-09-10 15:32 UTC, ataha24 commented on README.md
> +2. Conformes images to 1 mm isotropic resolution.
2. Conformes images to a desired isotropic resolution (default: 1mm).

2024-09-10 15:34 UTC, ataha24 commented on README.md
> +3. Executes intensity normalization (i.e., White Matter (WM) to 110) followed by min-max normalization.
3. Executes image intensity normalization by various supported algorithms (default: min-max normalization).

2024-09-10 15:38 UTC, ataha24 commented on autoafids_prep/workflow/scripts/tform_script.py
> +        coord_sys:: ??? (Ask Alaa)
str type

2024-09-10 15:41 UTC, ataha24 requested changes
I tested the workflow on CBS and performed as expected. I left some responses and comments but all very minor. We should be ready to merge this.

2024-09-11 13:15 UTC, Dhananjhay commented
All the above mentioned changes have been made. Ready to merge whenever you are!

2024-09-11 14:35 UTC, ataha24 approved these changes
Looks good!

2024-09-11 14:35 UTC, merged